
      - name: Prepare dist
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force dist | Out-Null
          Copy-Item build\ExtIO_RTL_FreqLabels.dll dist/
          Copy-Item freq_labels.csv dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ExtIO_RTL_FreqLabels
          path: dist

# (pri tagu) release s DLL + CSV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/ExtIO_RTL_FreqLabels.dll
            dist/freq_labels.csv
